name: Get and Print JWT

on:
  workflow_dispatch:

jobs:
  get-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Get OIDC Token
        id: get_token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken()
            core.setOutput('token', token)

      - name: Print JWT
        run: |
          echo "JWT Token:"
          echo "${{ steps.get_token.outputs.token }}"
          
          echo "Decoded JWT:"
          jwtd() {
            if [[ -x $(command -v jq) ]]; then
              jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
              echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
            fi
          }
          jwtd "${{ steps.get_token.outputs.token }}"
